### PR TITLE
Major refactor to svm and cnn

### PR DESCRIPTION
**Pull request by marcorossi5**
The idea is that all the models should have similar structure in the algorithm.

This will ease the integration of the Transformer as a feature extractor in the svm classifier.

### CODE REVIEW

**Comment by marcorossi5** [comment]
@rmoretti9, please have a look at the changes.
They mainly regard style and efficient coding, nothing really new from the conceptual point of view.

Try also to run the following commands representing the current pipeline (CNN + SVM) and let me know if you find any bug.

```bash
cd QuaKe
mkdir ../output/tmp
quake datagen cards/runcard.yaml -o ../output/tmp --force
quake train -o ../output/tmp -m cnn [-i]
quake train -o ../output/tmp -m svm [-i]
```
Remember, the `-i` flag is optional and allows to modify interactively the `runcard.yaml`. If you initially set the runcard, there's no need to put it.
Let me know, thanks.

**Comment by rmoretti9** [comment]
Hi @marcorossi5 
Thank you for this great update! 

The pipeline runs fine, unless I try to switch to 'True' here (cnn_dataloading.py):
    if False:
        projections[0] = roll_crop(projections[0], geo.nb_ybins // 2, geo.nb_zbins // 2)
        projections[1] = roll_crop(projections[1], geo.nb_xbins // 2, geo.nb_zbins // 2)
        projections[2] = roll_crop(projections[2], geo.nb_xbins // 2, geo.nb_ybins // 2)
Then it gives an error.

As far as I understood, the 'feature' layer of the CNN is now the LeakyReLU one. Why not extracting from the previous dense layer?

**Comment by marcorossi5** [comment]
> Then it gives an error.

Please, include the error in the comment the next time.  
I guess it is because `roll_crop` changes the inputs shape halving the resolution, then the `Dense` layer after `Flatten` is expecting a different input shape.

In order to make it work with `roll_crop` enabled, you have to change this line:
https://github.com/qismib/QuaKe/blob/2454f28a9c9cdc942ea3f8cbb196b6c6d6909a3f/src/quake/models/cnn/train.py#L58
to:
```
        nb_bins=[geo.nb_xbins // 2, geo.nb_ybins // 2, geo.nb_zbins // 2], **msetup["net_dict"]
```

> As far as I understood, the 'feature' layer of the CNN is now the LeakyReLU one. Why not extracting from the previous dense layer?

You should include a non linearity between two dense layers, to augment network expressiveness. If there is no linearity, two consecutive `Dense` layers are just a single linear transformation.
We might think about putting a `relu` instead of `lrelu` in this place, just to make features positives. `lrelu` only biases towards positive features.
Anyway, from the features point of view, it is the same to put the activation or not, that's not a big deal.

**Comment by marcorossi5** [comment]
The integration of the attention network into the pipeline should be complete now.

Please, find the updated pipeline in the following block:

```bash
cd QuaKe
mkdir ../output/tmp
quake datagen cards/runcard.yaml -o ../output/tmp --force

# train cnn + svm
quake train -o ../output/tmp -m cnn [-i]
quake train -o ../output/tmp -m svm [-i]

# train attention + svm
quake train -o ../output/tmp -m attention [-i]
quake train -o ../output/tmp -m svm --force [-i]
```

**Note:**
 The last command with `--force` flag will overwrite the previous svm output folder.
 At the moment, it is important that you are able to execute smoothly all jobs. We can tweak this in the future.

**Comment by marcorossi5** [comment]
Merging this as the pipeline is complete.

**Comment by rmoretti9** [comment]
Hi @marcorossi5 

Up to this, it's fine:
```
cd QuaKe
mkdir ../output/tmp
quake datagen cards/runcard.yaml -o ../output/tmp --force
quake train -o ../output/tmp -m cnn [-i]
```

When I run:
`quake train -o ../output/tmp -m svm [-i]`

I encounter this error:
```
[INFO] (quake.cnn) Loading weights at ../output/tmp/models/cnn/cnn.h5
Traceback (most recent call last):
  File "/root/TESI/.venv/bin/quake", line 33, in <module>
    sys.exit(load_entry_point('quake', 'console_scripts', 'quake')())
  File "/root/TESI/QuaKe/src/quake/scripts/quake.py", line 68, in main
    args.func(args)
  File "/root/TESI/QuaKe/src/quake/models/train.py", line 67, in train
    train_main(
  File "/root/TESI/QuaKe/src/quake/models/train.py", line 133, in train_main
    svm_train(data_folder, train_folder, setup)
  File "/root/TESI/QuaKe/src/quake/models/svm/train.py", line 215, in svm_train
    train_features, train_labels = extract_feats(
  File "/root/TESI/QuaKe/src/quake/models/svm/utils.py", line 36, in extract_feats
    _, features = fr.predict(generator)
  File "/root/TESI/QuaKe/src/quake/models/attention/AbstractNet.py", line 113, in predict
    outputs, features = self.model.predict(generator, **kwargs)
ValueError: too many values to unpack (expected 2)
```

And when I run:
`quake train -o ../output/tmp -m attention [-i]`

I get:
```
Epoch 1: val_acc improved from -inf to 0.62893, saving model to ../output/tmp/models/attention/attention.h5
Traceback (most recent call last):
  File "/root/TESI/.venv/bin/quake", line 33, in <module>
    sys.exit(load_entry_point('quake', 'console_scripts', 'quake')())
  File "/root/TESI/QuaKe/src/quake/scripts/quake.py", line 68, in main
    args.func(args)
  File "/root/TESI/QuaKe/src/quake/models/train.py", line 67, in train
    train_main(
  File "/root/TESI/QuaKe/src/quake/models/train.py", line 139, in train_main
    attention_train(data_folder, train_folder, setup)
  File "/root/TESI/QuaKe/src/quake/models/attention/train.py", line 173, in attention_train
    train_network(msetup, train_folder, network, (train_generator, val_generator))
  File "/root/TESI/QuaKe/src/quake/models/attention/train.py", line 139, in train_network
    network.fit(
  File "/root/TESI/.venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/root/TESI/QuaKe/src/quake/utils/callbacks.py", line 49, in on_epoch_end
    y_pred, features = self.model.predict_and_extract(self.validation_data)
AttributeError: 'AttentionNetwork' object has no attribute 'predict_and_extract'
```

**Pull request merged**
